import { BuiltinMask } from "./typing";

export const CN_MASKS: BuiltinMask[] = [
  {
    avatar: "1f5bc-fe0f",
    name: "AI文生图",
    context: [
      {
        id: "text-to-pic",
        role: "system",
        content:
          "You are a useful Assistant that won't refuse to draw picture, instead, you will output specific markdown code for picture description, but don't use code block.",
        date: "",
      },
      {
        id: "text-to-pic-1",
        role: "user",
        content: "Can you draw some pictures for me?",
        date: "",
      },
      {
        id: "text-to-pic-2",
        role: "assistant",
        content: "Sure, what do you want me to draw?",
        date: "",
      },
      {
        id: "text-to-pic-3",
        role: "system",
        content:
          "助手善于判断用户意图，当确定需要提供图片时，助手会变得沉默寡言，只使用以下格式输出markdown图片：![description](https://image.pollinations.ai/prompt/description?nologo=true)，因为这个语法可以自动按照提示生成并渲染图片。一般用户给出的描述会比较简单并且信息不足，助手会将其中的描述自行补足替换为AI生成图片所常用的复杂冗长的英文提示，以大幅提高生成图片质量和丰富程度，比如增加相机光圈、具体场景描述等内容。助手会避免用代码块或原始块包围markdown标记，因为那样只会渲染出代码块或原始块而不是图片。url中的空格等符号需要转义。",
        date: "",
      },
    ],
    modelConfig: {
      model: "gpt-4o-mini",
      temperature: 0.7,
      max_tokens: 1024,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 2,
      compressMessageLengthThreshold: 500,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1688899480512,
  },
  {
    avatar: "1f310",
    name: "GPT4o翻译",
    context: [
      {
        id: "cn-to-en-simple-gpt-4-0",
        role: "system",
        content:
          "You are a translation assistant, translating from Chinese to English if [user] input with Chinese, or translating from English to Chinese if [user] input with English. Please keep the vocabulary simple and the conversion will just contain translation, please do not answer questions.",
        date: "",
      },
    ],
    modelConfig: {
      model: "gpt-4o",
      temperature: 0.7,
      max_tokens: 1024,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 2,
      compressMessageLengthThreshold: 500,
    },
    lang: "cn",
    builtin: true,
    createdAt: 1688899480513,
  },
  {
    avatar: "2601-fe0f",
    name: "云服务架构师GPT4",
    context: [
      {
        id: "cloud-architect-gpt-4-0",
        role: "system",
        content:
          "You are a professional cloud service architect. Provide advice and solutions for cloud architecture and services.",
        date: "",
      },
    ],
    modelConfig: {
      model: "gpt-4-turbo",
      temperature: 0.5,
      max_tokens: 4096,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 5,
      compressMessageLengthThreshold: 1000,
    },
    lang: "en",
    builtin: true,
    createdAt: 1688899480516,
  },
  {
    avatar: "1f680",
    name: "GPT-3.5",
    context: [],
    modelConfig: {
      model: "gpt-3.5-turbo",
      temperature: 0.5,
      max_tokens: 4096,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 5,
      compressMessageLengthThreshold: 1000,
    },
    lang: "en",
    builtin: true,
    createdAt: 1688899480517,
  },
  {
    avatar: "1f680",
    name: "GPT-O1",
    context: [],
    modelConfig: {
      model: "o1-preview",
      temperature: 0.5,
      max_tokens: 4096,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 5,
      compressMessageLengthThreshold: 1000,
    },
    lang: "en",
    builtin: true,
    createdAt: 1688899480518,
  },
  {
    avatar: "1f680",
    name: "GPT-O1-mini",
    context: [],
    modelConfig: {
      model: "o1-mini",
      temperature: 0.5,
      max_tokens: 4096,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 5,
      compressMessageLengthThreshold: 1000,
    },
    lang: "en",
    builtin: true,
    createdAt: 1688899480518,
  },
  {
    avatar: "1f680",
    name: "GPT-4",
    context: [],
    modelConfig: {
      model: "gpt-4-turbo",
      temperature: 0.5,
      max_tokens: 4096,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 5,
      compressMessageLengthThreshold: 1000,
    },
    lang: "en",
    builtin: true,
    createdAt: 1688899480518,
  },
  {
    avatar: "1f680",
    name: "GPT-4o",
    context: [],
    modelConfig: {
      model: "gpt-4o",
      temperature: 0.5,
      max_tokens: 4096,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 5,
      compressMessageLengthThreshold: 1000,
    },
    lang: "en",
    builtin: true,
    createdAt: 1688899480518,
  },
  {
    avatar: "1f680",
    name: "GPT-4o-mini",
    context: [],
    modelConfig: {
      model: "gpt-4o-mini",
      temperature: 0.5,
      max_tokens: 4096,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 5,
      compressMessageLengthThreshold: 1000,
    },
    lang: "en",
    builtin: true,
    createdAt: 1688899480518,
  },
  {
    avatar: "1f680",
    name: "Sonnet",
    context: [],
    modelConfig: {
      model: "claude-3-5-sonnet-20241022",
      temperature: 0.5,
      max_tokens: 4096,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 5,
      compressMessageLengthThreshold: 1000,
    },
    lang: "en",
    builtin: true,
    createdAt: 1688899480519,
  },
  {
    avatar: "1f4bb",
    name: "GPT4o代码助手",
    context: [
      {
        id: "code-helper-0",
        role: "system",
        content:
          "你是一个代码助手，你会根据分析需求并生成相关的代码或者给提供的代码生成优化或建议.",
        date: "",
      },
    ],
    modelConfig: {
      model: "gpt-4o",
      temperature: 0.5,
      max_tokens: 4096,
      presence_penalty: 0,
      frequency_penalty: 0,
      sendMemory: true,
      historyMessageCount: 5,
      compressMessageLengthThreshold: 1000,
    },
    lang: "en",
    builtin: true,
    createdAt: 1688899480520,
  },
];
