name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  delete:
    branches: [ "main" ]
  create:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        JENKINS_JOB_NAME: ${{ secrets.JENKINS_JOB_NAME }}
      run: |
        tag=$(date +%s)
        docker build . --file Dockerfile -t ${DOCKER_HUB_USERNAME}/chatgpt-webui:${tag}
        docker tag ${DOCKER_HUB_USERNAME}/chatgpt-webui:${tag} ${DOCKER_HUB_USERNAME}/chatgpt-webui:latest
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
        docker push ${DOCKER_HUB_USERNAME}/chatgpt-webui:${tag}
        docker push ${DOCKER_HUB_USERNAME}/chatgpt-webui:latest
        curl -X POST ${JENKINS_URL}job/${JENKINS_JOB_NAME}/build?token=${JENKINS_TOKEN}
        
        
        
