name: Mirror to Gitee Repo

on: [ push, delete, create ]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee with white list
      uses: CeraceLee/hub-mirror-action@master
      with:
        src: github/CeraceLee
        dst: gitee/cerace
        dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        static_list: 'ChatGPT-Web'
        force_update: true
        debug: true
