name: Sync and Build

on: [ push, delete, create ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: CeraceLee/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:CeraceLee/ChatGPT-Web.git
          destination-repo: git@gitee.com:cerace/ChatGPT-Web.git
